import type { Config } from 'tailwindcss';

/**
 * Tailwind CSS configuration for Brand System Service.
 *
 * Imports generated token theme from Style Dictionary output.
 * Run `pnpm build:tokens` to regenerate tailwind-tokens.ts.
 *
 * @see BSS-2.2: Style Dictionary Build Pipeline
 * @see ADR-001: Static-First Architecture
 */

// eslint-disable-next-line @typescript-eslint/no-var-requires
let tailwindTokens: Record<string, unknown> = {};
try {
  // Generated by Style Dictionary — run `pnpm build:tokens` first
  tailwindTokens = require('./output/default/tailwind-tokens').default;
} catch {
  // Tokens not yet built — use empty theme extension
  console.warn('[tailwind.config] Token file not found. Run `pnpm build:tokens` to generate.');
}

const config: Config = {
  content: [
    './packages/*/src/**/*.{ts,tsx,html,hbs,ejs}',
    './templates/**/*.{html,hbs,ejs}',
  ],
  theme: {
    extend: tailwindTokens,
  },
  plugins: [],
};

export default config;
