/**
 * Static Package Exporter
 *
 * Produces a self-contained, download-ready ZIP of any generated static site.
 * Client can unzip, double-click index.html, and see their site — no server needed.
 *
 * BSS-5.8 — NFR-9.5: Static package portability.
 */

import fs from 'node:fs';
import path from 'node:path';
import archiver from 'archiver';
import { Open } from 'unzipper';
import { createLogger, type Logger } from '@bss/core';
import type { ExportOptions, ExportResult } from './types';
import { ExportError } from './types';

/**
 * README.txt content with deployment instructions.
 */
function generateReadmeContent(clientId: string, buildType: string): string {
  return `=== ${clientId.toUpperCase()} — ${buildType.toUpperCase()} ===
Generated by Brand System Service

=== HOW TO VIEW YOUR SITE LOCALLY ===
Double-click index.html in any modern browser.
No server or build step is required.

=== DEPLOY TO VERCEL ===
1. Visit vercel.com and sign in.
2. Click "Add New Project" → "Import" → upload this folder.
3. No build command needed. Output directory: / (root).

=== DEPLOY TO NETLIFY ===
1. Visit netlify.com and sign in.
2. Drag and drop this folder onto the Netlify dashboard.
3. Your site is live instantly.

=== DEPLOY TO GITHUB PAGES ===
1. Create a new GitHub repository.
2. Push all files from this folder to the main branch.
3. Enable GitHub Pages: Settings → Pages → Source: main / root.
`;
}

/**
 * Recursively collect all file paths in a directory.
 */
function collectAllFiles(dir: string): string[] {
  const results: string[] = [];

  function walk(currentDir: string): void {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else {
        results.push(fullPath);
      }
    }
  }

  walk(dir);
  return results;
}

/**
 * StaticPackageExporter creates download-ready ZIP archives from static builds.
 */
export class StaticPackageExporter {
  private readonly logger: Logger;

  constructor(logger?: Logger) {
    this.logger = logger ?? createLogger('StaticPackageExporter');
  }

  /**
   * Export a static build to a ZIP archive.
   *
   * Steps:
   * 1. Collect files from sourceDir
   * 2. Deduplicate if enabled
   * 3. Add to archive
   * 4. Inject README.txt if enabled
   * 5. Include sitemap/robots if present
   * 6. Finalize and verify
   */
  async export(options: ExportOptions): Promise<ExportResult> {
    const {
      clientId,
      buildType,
      sourceDir,
      outputPath,
      includeReadme = true,
      includeSitemap = true,
      deduplicateAssets = true,
    } = options;

    this.logger.info('Starting static package export', { clientId, buildType, sourceDir });

    // Validate sourceDir exists
    if (!fs.existsSync(sourceDir)) {
      throw new ExportError(
        `Source directory not found: ${sourceDir}`,
        outputPath
      );
    }

    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    fs.mkdirSync(outputDir, { recursive: true });

    // Collect all files
    const allFiles = collectAllFiles(sourceDir);
    if (allFiles.length === 0) {
      throw new ExportError(
        `Source directory is empty: ${sourceDir}`,
        outputPath
      );
    }

    // Create ZIP archive
    const output = fs.createWriteStream(outputPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    let fileCount = 0;
    archive.on('entry', () => { fileCount++; });

    archive.pipe(output);

    // Add files with optional deduplication
    const addedPaths = new Set<string>();
    for (const file of allFiles) {
      const relativePath = path.relative(sourceDir, file).replace(/\\/g, '/');

      // Skip sitemap.xml if includeSitemap is false
      if (relativePath === 'sitemap.xml' && !includeSitemap) {
        continue;
      }

      if (deduplicateAssets) {
        if (addedPaths.has(relativePath)) {
          this.logger.info(`Skipping duplicate: ${relativePath}`);
          continue;
        }
        addedPaths.add(relativePath);
      }

      archive.file(file, { name: relativePath });
    }

    // Inject README.txt
    if (includeReadme) {
      const readme = generateReadmeContent(clientId, buildType);
      archive.append(readme, { name: 'README.txt' });
    }

    // Finalize archive
    await new Promise<void>((resolve, reject) => {
      output.on('close', resolve);
      archive.on('error', reject);
      archive.finalize();
    });

    // Verify ZIP contains index.html
    await this.verifyZip(outputPath);

    // Get file stats
    const stats = fs.statSync(outputPath);
    const sizeKB = (stats.size / 1024).toFixed(1);

    this.logger.info(`Export complete: ${fileCount} files, ${sizeKB} KB`, {
      zipPath: outputPath,
      fileCount,
      sizeKB,
    });

    return {
      zipPath: outputPath,
      fileCount,
      sizeBytes: stats.size,
      sizeKB,
    };
  }

  /**
   * Verify the ZIP archive contains index.html.
   */
  private async verifyZip(zipPath: string): Promise<void> {
    const directory = await Open.file(zipPath);
    const hasIndex = directory.files.some(
      (f) => f.path === 'index.html' || f.path.endsWith('/index.html')
    );

    if (!hasIndex) {
      throw new ExportError(
        'ZIP verification failed: index.html not found in archive',
        zipPath
      );
    }
  }
}
