/**
 * Google Fonts Downloader for offline Brand Book packaging.
 *
 * Downloads woff2 font files from Google Fonts CSS2 API and generates
 * a local fonts.css with @font-face declarations using relative paths.
 *
 * Per AC-3 (BSS-2.8): Google Fonts <link> tags do not work on file://
 * protocol due to CORS restrictions. This module downloads and self-hosts them.
 */

import fs from 'node:fs';
import path from 'node:path';
import { createLogger, type Logger } from '@bss/core';

/**
 * Result of a font download operation.
 */
export interface FontDownloadResult {
  /** Number of font files downloaded */
  readonly filesDownloaded: number;
  /** Number of font files skipped (cached) */
  readonly filesSkipped: number;
  /** Path to generated fonts.css */
  readonly fontsCssPath: string;
}

/**
 * Parsed @font-face declaration from Google Fonts CSS.
 */
interface FontFaceEntry {
  readonly family: string;
  readonly style: string;
  readonly weight: string;
  readonly url: string;
  readonly unicodeRange?: string;
}

/**
 * Download Google Fonts woff2 files and generate a local fonts.css.
 *
 * @param families - Font family names (e.g., ['Inter', 'JetBrains Mono'])
 * @param outputDir - Brand book output directory (contains assets/)
 * @param debug - Enable debug logging
 * @returns Download result with counts
 */
export async function downloadGoogleFonts(
  families: string[],
  outputDir: string,
  debug = false
): Promise<FontDownloadResult> {
  const logger = createLogger('FontDownloader', debug);

  if (families.length === 0) {
    logger.warn('No font families specified, skipping download');
    return { filesDownloaded: 0, filesSkipped: 0, fontsCssPath: '' };
  }

  const fontsDir = path.join(outputDir, 'assets', 'fonts');
  const fontsCssPath = path.join(outputDir, 'assets', 'fonts.css');

  fs.mkdirSync(fontsDir, { recursive: true });

  let filesDownloaded = 0;
  let filesSkipped = 0;
  const fontFaceDeclarations: string[] = [];

  for (const family of families) {
    logger.info(`Processing font family: ${family}`);

    const entries = await fetchFontFaceEntries(family, logger);

    for (const entry of entries) {
      const filename = buildFontFilename(entry);
      const filePath = path.join(fontsDir, filename);

      if (fs.existsSync(filePath)) {
        logger.debug(`Cache hit: ${filename}`);
        filesSkipped++;
      } else {
        logger.info(`Downloading: ${filename}`);
        await downloadFile(entry.url, filePath, logger);
        filesDownloaded++;
      }

      fontFaceDeclarations.push(buildFontFaceRule(entry, filename));
    }
  }

  // Write fonts.css
  const cssContent = `/* Self-hosted fonts for offline Brand Book — Generated by @bss/static-generator */\n\n${fontFaceDeclarations.join('\n\n')}\n`;
  fs.writeFileSync(fontsCssPath, cssContent, 'utf-8');

  logger.info('Font download complete', {
    downloaded: filesDownloaded,
    cached: filesSkipped,
    fontsCssPath,
  });

  return { filesDownloaded, filesSkipped, fontsCssPath };
}

/**
 * Fetch @font-face entries from Google Fonts CSS2 API.
 *
 * Must send a modern User-Agent to receive woff2 format URLs.
 */
async function fetchFontFaceEntries(
  family: string,
  logger: Logger
): Promise<FontFaceEntry[]> {
  const weights = '400;500;600;700';
  const cssUrl = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weights}&display=swap`;

  logger.debug(`Fetching CSS: ${cssUrl}`);

  const response = await fetch(cssUrl, {
    headers: {
      'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    },
  });

  if (!response.ok) {
    throw new Error(
      `Failed to fetch Google Fonts CSS for "${family}": HTTP ${response.status}`
    );
  }

  const css = await response.text();
  return parseFontFaceCSS(css, family);
}

/**
 * Parse Google Fonts CSS response into FontFaceEntry objects.
 */
function parseFontFaceCSS(css: string, family: string): FontFaceEntry[] {
  const entries: FontFaceEntry[] = [];

  // Split by @font-face blocks
  const blocks = css.split('@font-face');

  for (const block of blocks) {
    if (!block.includes('url(')) continue;

    const urlMatch = block.match(/url\(([^)]+\.woff2)\)/);
    const weightMatch = block.match(/font-weight:\s*(\d+)/);
    const styleMatch = block.match(/font-style:\s*(\w+)/);
    const unicodeMatch = block.match(/unicode-range:\s*([^;]+)/);

    if (!urlMatch) continue;

    entries.push({
      family,
      style: styleMatch ? styleMatch[1] : 'normal',
      weight: weightMatch ? weightMatch[1] : '400',
      url: urlMatch[1],
      unicodeRange: unicodeMatch ? unicodeMatch[1].trim() : undefined,
    });
  }

  return entries;
}

/**
 * Build a deterministic filename for a font file.
 */
function buildFontFilename(entry: FontFaceEntry): string {
  const safeName = entry.family.replace(/\s+/g, '-').toLowerCase();
  const suffix = entry.unicodeRange
    ? `-${hashString(entry.unicodeRange)}`
    : '';
  return `${safeName}-${entry.style}-${entry.weight}${suffix}.woff2`;
}

/**
 * Simple string hash for creating unique suffixes.
 */
function hashString(str: string): string {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash + char) | 0;
  }
  return Math.abs(hash).toString(36).slice(0, 6);
}

/**
 * Build a @font-face CSS rule for a downloaded font.
 */
function buildFontFaceRule(entry: FontFaceEntry, filename: string): string {
  const lines = [
    '@font-face {',
    `  font-family: '${entry.family}';`,
    `  font-style: ${entry.style};`,
    `  font-weight: ${entry.weight};`,
    `  font-display: swap;`,
    `  src: url('./fonts/${filename}') format('woff2');`,
  ];

  if (entry.unicodeRange) {
    lines.push(`  unicode-range: ${entry.unicodeRange};`);
  }

  lines.push('}');
  return lines.join('\n');
}

/**
 * Download a file from a URL to a local path.
 */
async function downloadFile(
  url: string,
  destPath: string,
  logger: Logger
): Promise<void> {
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `Failed to download font file: HTTP ${response.status} from ${url}`
    );
  }

  const buffer = await response.arrayBuffer();
  fs.writeFileSync(destPath, Buffer.from(buffer));
  logger.debug(`Saved: ${destPath} (${buffer.byteLength} bytes)`);
}

/**
 * Extract Google Fonts family names from HTML <link> tags.
 *
 * Parses href attributes like:
 *   https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Roboto&display=swap
 *
 * @param htmlContent - HTML string to scan
 * @returns Array of unique font family names
 */
export function extractGoogleFontFamilies(htmlContent: string): string[] {
  const families = new Set<string>();

  const linkRegex =
    /href="https:\/\/fonts\.googleapis\.com\/css2?\?([^"]+)"/g;
  let match: RegExpExecArray | null;

  while ((match = linkRegex.exec(htmlContent)) !== null) {
    const queryString = match[1];
    const familyMatches = queryString.matchAll(/family=([^&]+)/g);

    for (const fm of familyMatches) {
      // Decode and extract family name (before colon for weight specs)
      const decoded = decodeURIComponent(fm[1]);
      const familyName = decoded.split(':')[0].replace(/\+/g, ' ');
      families.add(familyName);
    }
  }

  return [...families];
}
