/**
 * Shared HTML layout wrapper with brand token CSS injection.
 *
 * All training documents use this wrapper to ensure consistent
 * branding via CSS custom properties from the client token package.
 */
export function wrapLayout(
  title: string,
  clientName: string,
  primaryColor: string,
  bodyContent: string
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} — ${escapeHtml(clientName)}</title>
  <style>
    :root {
      --color-primary: ${escapeHtml(primaryColor)};
      --color-primary-light: ${escapeHtml(primaryColor)}1a;
      --color-text: #1a1a2e;
      --color-text-secondary: #4a4a6a;
      --color-bg: #ffffff;
      --color-bg-alt: #f8f9fa;
      --color-border: #e2e8f0;
      --font-heading: system-ui, -apple-system, sans-serif;
      --font-body: system-ui, -apple-system, sans-serif;
      --spacing-xs: 0.5rem;
      --spacing-sm: 1rem;
      --spacing-md: 1.5rem;
      --spacing-lg: 2rem;
      --spacing-xl: 3rem;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: var(--font-body);
      color: var(--color-text);
      background: var(--color-bg);
      line-height: 1.7;
      max-width: 800px;
      margin: 0 auto;
      padding: var(--spacing-lg);
    }
    h1 {
      font-family: var(--font-heading);
      color: var(--color-primary);
      font-size: 2rem;
      margin-bottom: var(--spacing-md);
      border-bottom: 3px solid var(--color-primary);
      padding-bottom: var(--spacing-sm);
    }
    h2 {
      font-family: var(--font-heading);
      color: var(--color-text);
      font-size: 1.4rem;
      margin-top: var(--spacing-xl);
      margin-bottom: var(--spacing-sm);
    }
    h3 {
      font-family: var(--font-heading);
      color: var(--color-text-secondary);
      font-size: 1.1rem;
      margin-top: var(--spacing-lg);
      margin-bottom: var(--spacing-xs);
    }
    p { margin-bottom: var(--spacing-sm); }
    ul, ol {
      margin-bottom: var(--spacing-sm);
      padding-left: var(--spacing-lg);
    }
    li { margin-bottom: var(--spacing-xs); }
    .header {
      background: var(--color-primary-light);
      padding: var(--spacing-lg);
      border-radius: 8px;
      margin-bottom: var(--spacing-xl);
    }
    .header p {
      color: var(--color-text-secondary);
      font-size: 0.95rem;
    }
    .section {
      background: var(--color-bg-alt);
      padding: var(--spacing-md);
      border-radius: 6px;
      margin-bottom: var(--spacing-md);
      border-left: 4px solid var(--color-primary);
    }
    .loom-placeholder {
      background: #fff3cd;
      border: 2px dashed #ffc107;
      border-radius: 8px;
      padding: var(--spacing-md);
      margin: var(--spacing-md) 0;
    }
    .loom-placeholder h3 { color: #856404; margin-top: 0; }
    .loom-placeholder .video-link {
      background: var(--color-primary);
      color: white;
      padding: 8px 16px;
      border-radius: 4px;
      text-decoration: none;
      display: inline-block;
      margin-top: var(--spacing-xs);
    }
    code {
      background: var(--color-bg-alt);
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 0.9em;
      color: var(--color-primary);
    }
    pre {
      background: #1a1a2e;
      color: #e2e8f0;
      padding: var(--spacing-md);
      border-radius: 6px;
      overflow-x: auto;
      margin-bottom: var(--spacing-sm);
    }
    pre code { background: none; color: inherit; padding: 0; }
    .footer {
      margin-top: var(--spacing-xl);
      padding-top: var(--spacing-md);
      border-top: 1px solid var(--color-border);
      color: var(--color-text-secondary);
      font-size: 0.85rem;
      text-align: center;
    }
    @media (max-width: 600px) {
      body { padding: var(--spacing-sm); }
      h1 { font-size: 1.5rem; }
    }
  </style>
</head>
<body>
${bodyContent}
  <div class="footer">
    <p>${escapeHtml(clientName)} Brand System — Training &amp; Enablement</p>
    <p>Generated by Brand System Service</p>
  </div>
</body>
</html>`;
}

/**
 * Generates the Loom video placeholder section.
 */
export function loomSection(
  title: string,
  duration: string,
  outline: readonly string[],
  url: string
): string {
  const videoLink = url
    ? `<a href="${escapeHtml(url)}" class="video-link" target="_blank" rel="noopener noreferrer">Watch Video</a>`
    : '<p><em>Video not yet recorded. Link will be added here once available.</em></p>';

  const outlineItems = outline.map((item) => `<li>${escapeHtml(item)}</li>`).join('\n        ');

  return `
  <div class="loom-placeholder">
    <h3>Video Walkthrough: ${escapeHtml(title)}</h3>
    <p><strong>Target Duration:</strong> ${escapeHtml(duration)}</p>
    <p><strong>Suggested Outline:</strong></p>
    <ol>
        ${outlineItems}
    </ol>
    ${videoLink}
  </div>`;
}

/**
 * Escapes HTML special characters to prevent XSS.
 */
export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
